import type { jsPDF } from 'jspdf';
import type { DailySalesReportRow } from './types';

export interface StockMovementReportTotals {
  grossUnitsSold: number;
  refundedUnits: number;
  reservedUnits: number;
  restockedUnits: number;
  netUnitsSold: number;
  costValue: number;
  retailValue: number;
}

interface CreateStockMovementReportOptions {
  rows: DailySalesReportRow[];
  date: string;
  generatedBy: string;
  terminalId: string;
  logoUrl: string;
}

const money = (value: number) => `R ${Math.round(Number(value) || 0).toLocaleString('en-ZA')}`.replace(/\u00a0/g, ' ');

export const calculateStockMovementReportTotals = (rows: DailySalesReportRow[]): StockMovementReportTotals => {
  const totals = rows.reduce<StockMovementReportTotals>((current, row) => {
    if (row.eventType === 'SALE') {
      current.grossUnitsSold += row.units;
      current.costValue += row.units * row.currentCostPrice;
      current.retailValue += row.units * row.currentSellingPrice;
    } else if (row.eventType === 'REFUND') current.refundedUnits += row.units;
    else if (row.eventType === 'RESERVE') current.reservedUnits += row.units;
    else if (row.eventType === 'RESTOCK') current.restockedUnits += row.units;
    return current;
  }, {
    grossUnitsSold: 0,
    refundedUnits: 0,
    reservedUnits: 0,
    restockedUnits: 0,
    netUnitsSold: 0,
    costValue: 0,
    retailValue: 0
  });
  totals.netUnitsSold = totals.grossUnitsSold - totals.refundedUnits;
  return totals;
};

const fetchDataUrl = async (url: string) => {
  try {
    const response = await fetch(url, { credentials: 'omit' });
    if (!response.ok) return '';
    const blob = await response.blob();
    return await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result || ''));
      reader.onerror = () => resolve('');
      reader.readAsDataURL(blob);
    });
  } catch {
    return '';
  }
};

const timeText = (value: string) => new Intl.DateTimeFormat('en-ZA', {
  timeZone: 'Africa/Johannesburg', hour: '2-digit', minute: '2-digit'
}).format(new Date(value));

export const createStockMovementReport = async ({
  rows,
  date,
  generatedBy,
  terminalId,
  logoUrl
}: CreateStockMovementReportOptions) => {
  const { jsPDF } = await import('jspdf');
  const doc: jsPDF = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4', compress: true });
  const totals = calculateStockMovementReportTotals(rows);
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  const headerBottom = 47;
  const footerTop = pageHeight - 10;
  const columns = [
    { label: 'Time', width: 15 },
    { label: 'Product', width: 63 },
    { label: 'Activity', width: 23 },
    { label: 'Units', width: 13 },
    { label: 'Qty Before > After', width: 28 },
    { label: 'Cost', width: 23 },
    { label: 'Selling', width: 23 },
    { label: 'Staff / Editor', width: 35 },
    { label: 'Terminal / Sheet', width: 31 },
    { label: 'Status', width: 21 }
  ];
  const logoData = await fetchDataUrl(logoUrl);

  const drawHeader = () => {
    doc.setFillColor(18, 18, 18);
    doc.rect(0, 0, pageWidth, 31, 'F');
    doc.setFillColor(226, 0, 26);
    doc.rect(0, 31, pageWidth, 2, 'F');
    if (logoData) {
      try { doc.addImage(logoData, 'PNG', margin, 5, 34, 20, undefined, 'FAST'); } catch { /* Keep report usable without the logo. */ }
    }
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('DAILY STOCK MOVEMENT REPORT', 50, 13);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Report date: ${date}  |  Generated by: ${generatedBy}  |  Terminal: ${terminalId}`, 50, 21);
    doc.setTextColor(35, 35, 35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text(`Sold ${totals.grossUnitsSold}`, margin, 39);
    doc.text(`Refunded ${totals.refundedUnits}`, 38, 39);
    doc.text(`Net ${totals.netUnitsSold}`, 72, 39);
    doc.text(`Restocked ${totals.restockedUnits}`, 99, 39);
    doc.text(`Cost value ${money(totals.costValue)}`, 139, 39);
    doc.text(`Retail value ${money(totals.retailValue)}`, 202, 39);
  };

  const drawTableHeader = (y: number) => {
    doc.setFillColor(226, 0, 26);
    doc.rect(margin, y, pageWidth - margin * 2, 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.7);
    let x = margin;
    columns.forEach((column) => {
      doc.text(column.label.toUpperCase(), x + 1.5, y + 4.6);
      x += column.width;
    });
  };

  const drawFooter = (pageNumber: number) => {
    doc.setDrawColor(205, 205, 205);
    doc.line(margin, footerTop - 2, pageWidth - margin, footerTop - 2);
    doc.setTextColor(90, 90, 90);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.text('GP Tyres & Mags - immutable stock movement audit', margin, footerTop + 2);
    doc.text(`Page ${pageNumber}`, pageWidth - margin, footerTop + 2, { align: 'right' });
  };

  let pageNumber = 1;
  let y = headerBottom;
  drawHeader();
  drawTableHeader(y);
  y += 7;

  rows.forEach((row, index) => {
    const values = [
      timeText(row.occurredAt),
      row.productDescription,
      `${row.eventType} / ${row.source.replaceAll('_', ' ')}`,
      String(row.units),
      `${row.quantityBefore ?? '-'} > ${row.quantityAfter ?? '-'}`,
      money(row.currentCostPrice),
      money(row.currentSellingPrice),
      row.staffOrEditor,
      row.terminalOrSheet,
      row.confidence === 'RECONSTRUCTED' ? 'RECONSTRUCTED' : 'VERIFIED'
    ];
    const wrapped = values.map((value, columnIndex) => doc.splitTextToSize(value, columns[columnIndex].width - 3) as string[]);
    const rowHeight = Math.max(8, ...wrapped.map((lines) => lines.length * 3.1 + 3));
    if (y + rowHeight > footerTop - 4) {
      drawFooter(pageNumber);
      doc.addPage('a4', 'landscape');
      pageNumber += 1;
      drawHeader();
      y = headerBottom;
      drawTableHeader(y);
      y += 7;
    }
    if (index % 2 === 0) {
      doc.setFillColor(247, 247, 247);
      doc.rect(margin, y, pageWidth - margin * 2, rowHeight, 'F');
    }
    if (row.confidence === 'RECONSTRUCTED') {
      doc.setFillColor(255, 248, 225);
      doc.rect(margin, y, pageWidth - margin * 2, rowHeight, 'F');
    }
    doc.setDrawColor(225, 225, 225);
    doc.line(margin, y + rowHeight, pageWidth - margin, y + rowHeight);
    doc.setTextColor(35, 35, 35);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.6);
    let x = margin;
    wrapped.forEach((lines, columnIndex) => {
      doc.text(lines, x + 1.5, y + 4.2);
      x += columns[columnIndex].width;
    });
    y += rowHeight;
  });

  if (!rows.length) {
    doc.setTextColor(95, 95, 95);
    doc.setFontSize(11);
    doc.text('No recorded stock movement for this date.', pageWidth / 2, y + 18, { align: 'center' });
  }
  drawFooter(pageNumber);
  return { doc, fileName: `gp-tyres-stock-movement-${date}.pdf`, totals };
};
