// Generated from complete Codex browser catalogue and individual product-page captures.
// Website prices already include VAT; no VAT is added again.
export const HOOSIER_CATALOG_SOURCE_URL = "https://hoosiertyres.co.za/shop/";
export const HOOSIER_CATALOG_SYNCED_AT = "2026-09-10T09:18:49.985Z";
export const HOOSIER_ROWS = [
  {
    "websiteProductId": 322,
    "supplierSku": "46935A7",
    "brand": "HOOSIER",
    "pattern": "A7 Racing Radial",
    "size": "P295/30ZR19",
    "category": "Racing Tyres",
    "productName": "Hoosier A7 Racing Radial – P295/30ZR19",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 10000,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-R7-A7-Racing-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p295-30zr19a7-46935a7/",
    "sourceSpecifications": "Item Code: 46935A7\nSize: P295/30ZR19\nConstruction: Radial\nCompound: A7 (maximum peak grip, short lifespan)\nTread: Semi-slick with minimal grooves\nApplication: Competition / dry track use\nA7 Compound:",
    "sourceRestrictions": "⚠ Track use only — not road legal. DOT-labelled for transport, not for road driving.",
    "capturedAt": "2026-09-10T09:15:49.381Z"
  },
  {
    "websiteProductId": 306,
    "supplierSku": "43164R20",
    "brand": "HOOSIER",
    "pattern": "Dirt Oval Tyre R20",
    "size": "20.5X7.0-13",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Dirt Oval Tyre R20 — 20.5×7.0-13",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 5450,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-20-5x7-0-13r20-43164r20/",
    "sourceSpecifications": "Size: 20.5×7.0-13\nCompound: R20\nApplication: Dirt oval racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:16:48.698Z"
  },
  {
    "websiteProductId": 307,
    "supplierSku": "43167R35B",
    "brand": "HOOSIER",
    "pattern": "Dirt Oval Tyre R35B",
    "size": "20.0X7.5-13",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Dirt Oval Tyre R35B — 20.0×7.5-13",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 5850,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-20-0x7-5-13r35b-43167r35b/",
    "sourceSpecifications": "Size: 20.0×7.5-13\nCompound: R35B\nApplication: Dirt oval racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:16:49.402Z"
  },
  {
    "websiteProductId": 17,
    "supplierSku": "17310DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P225/50R15",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P225/50R15",
    "stockUnits": 8,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "8 in stock",
    "sellingPrice": 6850,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-dot-drag-radial-tires-225-50r15/",
    "sourceSpecifications": "Item Code: 17310DR2\nSize: P225/50R15\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:16:50.060Z"
  },
  {
    "websiteProductId": 15,
    "supplierSku": "17327DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P225/50R17",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P225/50R17",
    "stockUnits": 1,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "1 in stock",
    "sellingPrice": 8450,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-d-o-t-radial-drag-racing-tire-p225-45r-17/",
    "sourceSpecifications": "Item Code: 17327DR2\nSize: P225/50R17\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:16:50.694Z"
  },
  {
    "websiteProductId": 19,
    "supplierSku": "17314DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P235/60R15",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P235/60R15",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 6875,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-dot-drag-radial-tires-235-60-15/",
    "sourceSpecifications": "Item Code: 17314DR2\nSize: P235/60R15\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:16:51.350Z"
  },
  {
    "websiteProductId": 29,
    "supplierSku": "17340DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P245/40R18",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P245/40R18",
    "stockUnits": 3,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "3 in stock",
    "sellingPrice": 8750,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-dot-drag-radial-tires-245-40-18/",
    "sourceSpecifications": "Item Code: 17340DR2\nSize: P245/40R18\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:16:51.994Z"
  },
  {
    "websiteProductId": 23,
    "supplierSku": "17328DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P245/45R17",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P245/45R17",
    "stockUnits": 1,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "1 in stock",
    "sellingPrice": 8550,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-dot-drag-radial-tires-245-45-17/",
    "sourceSpecifications": "Item Code: 17328DR2\nSize: P245/45R17\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:16:52.646Z"
  },
  {
    "websiteProductId": 25,
    "supplierSku": "17330DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P275/40R17",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P275/40R17",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 8650,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-dot-drag-radial-tires-275-40-17/",
    "sourceSpecifications": "Item Code: 17330DR2\nSize: P275/40R17\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:16:53.275Z"
  },
  {
    "websiteProductId": 111,
    "supplierSku": "17315DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P275/50R15",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P275/50R15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 6975,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-d-o-t-radial-drag-racing-tire-p275-50r-15-17315dr2/",
    "sourceSpecifications": "Item Code: 17315DR2\nSize: P275/50R15\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:17:32.678Z"
  },
  {
    "websiteProductId": 31,
    "supplierSku": "17342DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P315/30R18",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P315/30R18",
    "stockUnits": 6,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "6 in stock",
    "sellingPrice": 8975,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-dot-drag-radial-tires-315-30-18/",
    "sourceSpecifications": "Item Code: 17342DR2\nSize: P315/30R18\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:17:33.305Z"
  },
  {
    "websiteProductId": 27,
    "supplierSku": "17332DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P315/35R17",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P315/35R17",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 8875,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-dot-drag-radial-tires-315-35-17/",
    "sourceSpecifications": "Item Code: 17332DR2\nSize: P315/35R17\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:17:33.909Z"
  },
  {
    "websiteProductId": 283,
    "supplierSku": "17318DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P325/50R15",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P325/50R15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 7500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p325-50r15-17318dr2/",
    "sourceSpecifications": "Item Code: 17318DR2\nSize: P325/50R15\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:17:34.501Z"
  },
  {
    "websiteProductId": 292,
    "supplierSku": "18085",
    "brand": "HOOSIER",
    "pattern": "Drag Front Tyre",
    "size": "23.0/5.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Front Tyre – 23.0/5.0-15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 4150,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Front-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-23-0-5-0-15-18085/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:17:35.161Z"
  },
  {
    "websiteProductId": 33,
    "supplierSku": "18112",
    "brand": "HOOSIER",
    "pattern": "Drag Front Tyre",
    "size": "28.0/4.5-18",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Front Tyre – 28.0/4.5-18",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 4450,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Front-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-drag-front-tires-28-4-5-15/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:17:35.765Z"
  },
  {
    "websiteProductId": 296,
    "supplierSku": "18105",
    "brand": "HOOSIER",
    "pattern": "Drag Front Tyre",
    "size": "26.0/4.5-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Front Tyre — 26.0/4.5-15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 4300,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Front-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-26-0-4-5-15-18105/",
    "sourceSpecifications": "Size: 26.0/4.5-15\nConstruction: Bias-ply\nApplication: Drag racing front (steer) tyre",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal.",
    "capturedAt": "2026-09-10T09:17:36.376Z"
  },
  {
    "websiteProductId": 295,
    "supplierSku": "18103",
    "brand": "HOOSIER",
    "pattern": "Drag Front Tyre",
    "size": "26.0/4.5-17",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Front Tyre — 26.0/4.5-17",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 4300,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Front-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-26-0-4-5-17-18103/",
    "sourceSpecifications": "Size: 26.0/4.5-17\nConstruction: Bias-ply\nApplication: Drag racing front (steer) tyre",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal.",
    "capturedAt": "2026-09-10T09:17:36.965Z"
  },
  {
    "websiteProductId": 41,
    "supplierSku": "18060",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "24.5/8.0-13",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 24.5/8.0-13",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 6650,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-drag-racing-slicks-24-5-9-13-18060d06/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:17:38.701Z"
  },
  {
    "websiteProductId": 35,
    "supplierSku": "18110",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "26.0/8.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 26.0/8.0-15",
    "stockUnits": 6,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "6 in stock",
    "sellingPrice": 6800,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-drag-racing-slicks-26-8-15/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:17:39.319Z"
  },
  {
    "websiteProductId": 297,
    "supplierSku": "18120",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "26.0/9.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 26.0/9.0-15",
    "stockUnits": 6,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "6 in stock",
    "sellingPrice": 6900,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-26-0-9-0-15-18120/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:17:39.897Z"
  },
  {
    "websiteProductId": 298,
    "supplierSku": "18150",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "28.0/10.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 28.0/10.0-15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 7750,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-28-0-10-0-15-18150/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:17:40.474Z"
  },
  {
    "websiteProductId": 37,
    "supplierSku": "18190",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "29.0/12.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 29.0/12.0-15",
    "stockUnits": 5,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "5 in stock",
    "sellingPrice": 9350,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-drag-racing-slicks-29-12-15/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:17:41.063Z"
  },
  {
    "websiteProductId": 299,
    "supplierSku": "18156",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "28.0/10.5-15W",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick — 28.0/10.5-15W",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 7850,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-28-0-10-5-15w-18156/",
    "sourceSpecifications": "Size: 28.0/10.5-15W\nConstruction: Bias-ply\nApplication: High horsepower drag racing",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal.",
    "capturedAt": "2026-09-10T09:17:41.648Z"
  },
  {
    "websiteProductId": 301,
    "supplierSku": "18240",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "31.0/14.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick — 31.0/14.0-15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 11750,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-31-0-14-0-15-18240/",
    "sourceSpecifications": "Size: 31.0/14.0-15\nConstruction: Bias-ply\nApplication: Drag racing slick (rear application)",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. Not intended for daily driving or wet conditions.",
    "capturedAt": "2026-09-10T09:17:42.244Z"
  },
  {
    "websiteProductId": 314,
    "supplierSku": "44308HOTDR",
    "brand": "HOOSIER",
    "pattern": "Hot Rod Dirt Modified",
    "size": "26.5X9.5-15",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Hot Rod Dirt Modified — 26.5×9.5-15",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 7500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-26-5x9-5-15-44308hotdr/",
    "sourceSpecifications": "Size: 26.5×9.5-15\nConstruction: Bias-ply\nApplication: Hot Rod Dirt Modified racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:17:42.845Z"
  },
  {
    "websiteProductId": 252,
    "supplierSku": "22368R55",
    "brand": "HOOSIER",
    "pattern": "Kart Tyre R55 Shifter Rear",
    "size": "7.1/11.0-5",
    "category": "Karting",
    "productName": "Hoosier Kart Tyre R55 Shifter Rear — 7.1/11.0-5",
    "stockUnits": 24,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "24 in stock",
    "sellingPrice": 1250,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Kart-Slick-Tire.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-shifter-kart-r55-rear-7-1-11-0-5/",
    "sourceSpecifications": "Size: 7.1/11.0-5\nCompound: R55 (Soft, shifter-spec)\nApplication: 125cc shifter / gearbox kart racing",
    "sourceRestrictions": "⚠ Designed for kart racing only — not intended for road use.",
    "capturedAt": "2026-09-10T09:17:43.521Z"
  },
  {
    "websiteProductId": 303,
    "supplierSku": "22380R70",
    "brand": "HOOSIER",
    "pattern": "Kart Tyre R70 Rear",
    "size": "7.1/11.0-5",
    "category": "Karting",
    "productName": "Hoosier Kart Tyre R70 Rear — 7.1/11.0-5",
    "stockUnits": 12,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "12 in stock",
    "sellingPrice": 1250,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Kart-Slick-Tire.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-7-1-11-0-5r70-22380r70/",
    "sourceSpecifications": "Item Code: 22380R70\nSize: 7.1/11.0-5\nCompound: Medium (R70)\nApplication: Kart Racing\nCompound Quick Guide:",
    "sourceRestrictions": "⚠ Designed for kart racing use only. Not intended for road use.",
    "capturedAt": "2026-09-10T09:17:44.133Z"
  },
  {
    "websiteProductId": 311,
    "supplierSku": "43851S100",
    "brand": "HOOSIER",
    "pattern": "Late Model Dirt S100",
    "size": "280/680R18",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Late Model Dirt S100 — 280/680R18",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 5000,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-280-680r18-43851s100/",
    "sourceSpecifications": "Size: 280/680R18\nCompound: S100\nApplication: Late model dirt racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:17:59.979Z"
  },
  {
    "websiteProductId": 279,
    "supplierSku": "17191",
    "brand": "HOOSIER",
    "pattern": "Motorcycle Race Tyre",
    "size": "110/90-19",
    "category": "Motorcycle",
    "productName": "Hoosier Motorcycle Race Tyre – 110/90-19",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 1750,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/woocommerce-placeholder-300x300.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-110-90-19-17191/",
    "sourceSpecifications": "Item Code: 17191\nSize: 110/90-19\nApplication: Motorcycle Race / Track",
    "sourceRestrictions": "⚠ Hoosier motorcycle race tyres are sold by compound + application. Contact us before ordering to confirm the correct compound for your discipline (sprint, endurance, flat track, etc.).",
    "capturedAt": "2026-09-10T09:18:00.648Z"
  },
  {
    "websiteProductId": 280,
    "supplierSku": "7200",
    "brand": "HOOSIER",
    "pattern": "Motorcycle Race Tyre",
    "size": "120/80-19",
    "category": "Motorcycle",
    "productName": "Hoosier Motorcycle Race Tyre – 120/80-19",
    "stockUnits": 1,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "1 in stock",
    "sellingPrice": 1750,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/woocommerce-placeholder-300x300.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-120-80-19-7200/",
    "sourceSpecifications": "Item Code: 7200\nSize: 120/80-19\nApplication: Motorcycle Race / Track",
    "sourceRestrictions": "⚠ Hoosier motorcycle race tyres are sold by compound + application. Contact us before ordering to confirm the correct compound for your discipline (sprint, endurance, flat track, etc.).",
    "capturedAt": "2026-09-10T09:18:01.403Z"
  },
  {
    "websiteProductId": 313,
    "supplierSku": "44305RX",
    "brand": "HOOSIER",
    "pattern": "Outlaw Dirt RX",
    "size": "200/530R13DH",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Outlaw Dirt RX — 200/530R13DH",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 2500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/06/TYRE.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-200-530r13dh-44305rx/",
    "sourceSpecifications": "Size: 200/530R13DH\nCompound: RX\nApplication: Outlaw / open dirt oval racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:18:02.021Z"
  },
  {
    "websiteProductId": 285,
    "supplierSku": "17510QTPRO",
    "brand": "HOOSIER",
    "pattern": "QT Pro Drag Tyre",
    "size": "27.0X11.5-15LT",
    "category": "Drag Tyres",
    "productName": "Hoosier QT Pro Drag Tyre – 27.0×11.5-15LT",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 7850,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-QT-Pro-Drag-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-27-0x11-5-15lt-17510qtpro/",
    "sourceSpecifications": "Item Code: 17510QTPRO\nSize: 27.0×11.5-15LT\nConstruction: Bias-ply\nCompound: Soft drag (Quick Time Pro)\nTread: DOT-labelled, slick-style with minimal grooves\nApplication: Drag racing / dry strip use, limited street/strip\nWhere QT Pro Sits:",
    "sourceRestrictions": "⚠ Drag racing focused — DOT-labelled but not intended for daily driving.",
    "capturedAt": "2026-09-10T09:18:02.620Z"
  },
  {
    "websiteProductId": 286,
    "supplierSku": "17601QTPRO",
    "brand": "HOOSIER",
    "pattern": "QT Pro Drag Tyre",
    "size": "28.0X11.5-15LT",
    "category": "Drag Tyres",
    "productName": "Hoosier QT Pro Drag Tyre – 28.0×11.5-15LT",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 8150,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-QT-Pro-Drag-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-28-0x11-5-15lt-17601qtpro/",
    "sourceSpecifications": "Item Code: 17601QTPRO\nSize: 28.0×11.5-15LT\nConstruction: Bias-ply\nCompound: Soft drag (Quick Time Pro)\nTread: DOT-labelled, slick-style with minimal grooves\nApplication: Drag racing / dry strip use, limited street/strip\nWhere QT Pro Sits:",
    "sourceRestrictions": "⚠ Drag racing focused — DOT-labelled but not intended for daily driving.",
    "capturedAt": "2026-09-10T09:18:03.206Z"
  },
  {
    "websiteProductId": 288,
    "supplierSku": "17611QTPRO",
    "brand": "HOOSIER",
    "pattern": "QT Pro Drag Tyre",
    "size": "28.0X14.5-15LT",
    "category": "Drag Tyres",
    "productName": "Hoosier QT Pro Drag Tyre – 28.0×14.5-15LT",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 8750,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-QT-Pro-Drag-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-28-0x14-5-15lt-17611qtpro/",
    "sourceSpecifications": "Item Code: 17611QTPRO\nSize: 28.0×14.5-15LT\nConstruction: Bias-ply\nCompound: Soft drag (Quick Time Pro)\nTread: DOT-labelled, slick-style with minimal grooves\nApplication: Drag racing / dry strip use, limited street/strip\nWhere QT Pro Sits:",
    "sourceRestrictions": "⚠ Drag racing focused — DOT-labelled but not intended for daily driving.",
    "capturedAt": "2026-09-10T09:18:03.811Z"
  },
  {
    "websiteProductId": 320,
    "supplierSku": "46601R7",
    "brand": "HOOSIER",
    "pattern": "R7 Racing Radial",
    "size": "P205/45ZR16",
    "category": "Racing Tyres",
    "productName": "Hoosier R7 Racing Radial – P205/45ZR16",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 5300,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-R7-A7-Racing-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p205-45zr16-46601r7/",
    "sourceSpecifications": "Item Code: 46601R7\nSize: P205/45ZR16\nConstruction: Radial\nCompound: R7 (track-focused)\nTread: Semi-slick with minimal grooves\nApplication: Competition / dry track use\nR7 Compound:",
    "sourceRestrictions": "⚠ Track use only — not road legal. DOT-labelled for transport, not for road driving.",
    "capturedAt": "2026-09-10T09:18:04.409Z"
  },
  {
    "websiteProductId": 316,
    "supplierSku": "46304R7",
    "brand": "HOOSIER",
    "pattern": "R7 Racing Radial",
    "size": "P205/60ZR13",
    "category": "Racing Tyres",
    "productName": "Hoosier R7 Racing Radial – P205/60ZR13",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 4850,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-R7-A7-Racing-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p205-60zr13-46304r7/",
    "sourceSpecifications": "Item Code: 46304R7\nSize: P205/60ZR13\nConstruction: Radial\nCompound: R7 (track-focused)\nTread: Semi-slick with minimal grooves\nApplication: Competition / dry track use\nR7 Compound:",
    "sourceRestrictions": "⚠ Track use only — not road legal. DOT-labelled for transport, not for road driving.",
    "capturedAt": "2026-09-10T09:18:04.988Z"
  },
  {
    "websiteProductId": 317,
    "supplierSku": "46511R7",
    "brand": "HOOSIER",
    "pattern": "R7 Racing Radial",
    "size": "P225/45ZR15",
    "category": "Racing Tyres",
    "productName": "Hoosier R7 Racing Radial – P225/45ZR15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 5350,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-R7-A7-Racing-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p225-45zr15-46511r7/",
    "sourceSpecifications": "Item Code: 46511R7\nSize: P225/45ZR15\nConstruction: Radial\nCompound: R7 (track-focused)\nTread: Semi-slick with minimal grooves\nApplication: Competition / dry track use\nR7 Compound:",
    "sourceRestrictions": "⚠ Track use only — not road legal. DOT-labelled for transport, not for road driving.",
    "capturedAt": "2026-09-10T09:18:05.581Z"
  },
  {
    "websiteProductId": 321,
    "supplierSku": "46611R7",
    "brand": "HOOSIER",
    "pattern": "R7 Racing Radial",
    "size": "P225/45ZR16",
    "category": "Racing Tyres",
    "productName": "Hoosier R7 Racing Radial – P225/45ZR16",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 5500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-R7-A7-Racing-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p225-45zr16-46611r7/",
    "sourceSpecifications": "Item Code: 46611R7\nSize: P225/45ZR16\nConstruction: Radial\nCompound: R7 (track-focused)\nTread: Semi-slick with minimal grooves\nApplication: Competition / dry track use\nR7 Compound:",
    "sourceRestrictions": "⚠ Track use only — not road legal. DOT-labelled for transport, not for road driving.",
    "capturedAt": "2026-09-10T09:18:06.219Z"
  },
  {
    "websiteProductId": 318,
    "supplierSku": "46522R7",
    "brand": "HOOSIER",
    "pattern": "R7 Racing Radial",
    "size": "P245/40ZR15",
    "category": "Racing Tyres",
    "productName": "Hoosier R7 Racing Radial – P245/40ZR15",
    "stockUnits": 2,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "2 in stock",
    "sellingPrice": 5700,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-R7-A7-Racing-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p245-40zr15-46522r7/",
    "sourceSpecifications": "Item Code: 46522R7\nSize: P245/40ZR15\nConstruction: Radial\nCompound: R7 (track-focused)\nTread: Semi-slick with minimal grooves\nApplication: Competition / dry track use\nR7 Compound:",
    "sourceRestrictions": "⚠ Track use only — not road legal. DOT-labelled for transport, not for road driving.",
    "capturedAt": "2026-09-10T09:18:06.900Z"
  },
  {
    "websiteProductId": 319,
    "supplierSku": "46536R7",
    "brand": "HOOSIER",
    "pattern": "R7 Racing Radial",
    "size": "P275/35ZR15",
    "category": "Racing Tyres",
    "productName": "Hoosier R7 Racing Radial – P275/35ZR15",
    "stockUnits": 6,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "6 in stock",
    "sellingPrice": 5900,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-R7-A7-Racing-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p275-35zr15-46536r7/",
    "sourceSpecifications": "Item Code: 46536R7\nSize: P275/35ZR15\nConstruction: Radial\nCompound: R7 (track-focused)\nTread: Semi-slick with minimal grooves\nApplication: Competition / dry track use\nR7 Compound:",
    "sourceRestrictions": "⚠ Track use only — not road legal. DOT-labelled for transport, not for road driving.",
    "capturedAt": "2026-09-10T09:18:07.590Z"
  },
  {
    "websiteProductId": 75,
    "supplierSku": "47836",
    "brand": "HOOSIER",
    "pattern": "Track Attack Pro",
    "size": "275/35ZR18",
    "category": "Racing Tyres",
    "productName": "Hoosier Track Attack Pro – 275/35ZR18",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 9375,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Track-Attack-Pro.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-track-attack-pro-275-35-18/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:08.290Z"
  },
  {
    "websiteProductId": 105,
    "supplierSku": "47970",
    "brand": "HOOSIER",
    "pattern": "Track Attack Pro",
    "size": "285/30ZR20",
    "category": "Racing Tyres",
    "productName": "Hoosier Track Attack Pro – 285/30ZR20",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 10250,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Track-Attack-Pro.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-track-attack-pro-285-30-20/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:08.875Z"
  },
  {
    "websiteProductId": 91,
    "supplierSku": "47934",
    "brand": "HOOSIER",
    "pattern": "Track Attack Pro",
    "size": "285/35ZR19",
    "category": "Racing Tyres",
    "productName": "Hoosier Track Attack Pro – 285/35ZR19",
    "stockUnits": 4,
    "orderStatus": "AVAILABLE",
    "websiteStockDetail": "4 in stock",
    "sellingPrice": 9950,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Track-Attack-Pro.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-track-attack-pro-285-35-19/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:09.466Z"
  },
  {
    "websiteProductId": 308,
    "supplierSku": "43181H10SA",
    "brand": "HOOSIER",
    "pattern": "Dirt Oval Tyre H10SA",
    "size": "20.0X9.0-13",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Dirt Oval Tyre H10SA — 20.0×9.0-13",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 4350,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-20-0x9-0-13h10sa-43181h10sa/",
    "sourceSpecifications": "Size: 20.0×9.0-13\nCompound: H10SA\nApplication: Dirt oval racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:18:10.156Z"
  },
  {
    "websiteProductId": 309,
    "supplierSku": "43654MS",
    "brand": "HOOSIER",
    "pattern": "Dirt Oval Tyre MS",
    "size": "23.5X11.0R16",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Dirt Oval Tyre MS — 23.5×11.0R16",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 9750,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-23-5x11-0r16-43654ms/",
    "sourceSpecifications": "Size: 23.5×11.0R16\nCompound: MS\nApplication: Dirt oval racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:18:10.773Z"
  },
  {
    "websiteProductId": 310,
    "supplierSku": "43673MS",
    "brand": "HOOSIER",
    "pattern": "Dirt Oval Tyre MS",
    "size": "25.5X12.0R16",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Dirt Oval Tyre MS — 25.5×12.0R16",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 10300,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-25-5x12-0r16-43673ms/",
    "sourceSpecifications": "Size: 25.5×12.0R16\nCompound: MS\nApplication: Dirt oval racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:18:11.413Z"
  },
  {
    "websiteProductId": 284,
    "supplierSku": "17343DR2",
    "brand": "HOOSIER",
    "pattern": "DR2 Drag Radial",
    "size": "P325/45R18",
    "category": "Drag Tyres",
    "productName": "Hoosier DR2 Drag Radial – P325/45R18",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 9100,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DR2-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-p325-45r18-17343dr2/",
    "sourceSpecifications": "Item Code: 17343DR2\nSize: P325/45R18\nConstruction: Radial\nCompound: DR2 (drag radial — high traction)\nTread: Semi-slick with minimal grooves\nApplication: Drag racing / dry strip use\nDR2 Compound:",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. DOT-labelled for transport, not for daily driving.",
    "capturedAt": "2026-09-10T09:18:12.047Z"
  },
  {
    "websiteProductId": 293,
    "supplierSku": "18095",
    "brand": "HOOSIER",
    "pattern": "Drag Front Tyre",
    "size": "24.0/5.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Front Tyre – 24.0/5.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 4200,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Front-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-24-0-5-0-15-18095/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:39.801Z"
  },
  {
    "websiteProductId": 294,
    "supplierSku": "18102",
    "brand": "HOOSIER",
    "pattern": "Drag Front Tyre",
    "size": "25.0/5.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Front Tyre – 25.0/5.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 4250,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Front-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-25-0-5-0-15-18102/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:40.451Z"
  },
  {
    "websiteProductId": 290,
    "supplierSku": "18062",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "24.5/8.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 24.5/8.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 6850,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-24-5-8-0-15-18062/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:41.133Z"
  },
  {
    "websiteProductId": 291,
    "supplierSku": "18063",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "24.5/9.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 24.5/9.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 6875,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-24-5-9-0-15-18063/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:41.745Z"
  },
  {
    "websiteProductId": 45,
    "supplierSku": "18131",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "26.0/10.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 26.0/10.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 6950,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-drag-racing-slick-26-0-10-0-15-d06-18131d06/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:42.373Z"
  },
  {
    "websiteProductId": 302,
    "supplierSku": "18250",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "32.0/14.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 32.0/14.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 12000,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-32-0-14-0-15-18250/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:42.996Z"
  },
  {
    "websiteProductId": 43,
    "supplierSku": "18350",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "33.0/12.0-15",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick – 33.0/12.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 11850,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-drag-racing-slick-33-0-12-0-15-c09-18350c09/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:43.683Z"
  },
  {
    "websiteProductId": 300,
    "supplierSku": "18157",
    "brand": "HOOSIER",
    "pattern": "Drag Slick",
    "size": "28.0/10.0-17",
    "category": "Drag Tyres",
    "productName": "Hoosier Drag Slick — 28.0/10.0-17",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 7800,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Drag-Slick.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-28-0-10-0-17-18157/",
    "sourceSpecifications": "Size: 28.0/10.0-17\nConstruction: Bias-ply\nApplication: Drag racing slick (rear application)",
    "sourceRestrictions": "⚠ Drag racing use only — not road legal. Not intended for daily driving or wet conditions.",
    "capturedAt": "2026-09-10T09:18:44.296Z"
  },
  {
    "websiteProductId": 312,
    "supplierSku": "44287HOTDR",
    "brand": "HOOSIER",
    "pattern": "Hot Rod Dirt Modified",
    "size": "25.5X8.5-15",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Hot Rod Dirt Modified — 25.5×8.5-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 7500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-25-5x8-5-15-44287hotdr/",
    "sourceSpecifications": "Size: 25.5×8.5-15\nConstruction: Bias-ply\nApplication: Hot Rod Dirt Modified racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:18:44.965Z"
  },
  {
    "websiteProductId": 315,
    "supplierSku": "44309HOTDR",
    "brand": "HOOSIER",
    "pattern": "Hot Rod Dirt Modified",
    "size": "26.5X11.0-15",
    "category": "Dirt Oval Tyres",
    "productName": "Hoosier Hot Rod Dirt Modified — 26.5×11.0-15",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 7500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-Dirt-Oval.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-26-5x11-0-15-44309hotdr/",
    "sourceSpecifications": "Size: 26.5×11.0-15\nConstruction: Bias-ply\nApplication: Hot Rod Dirt Modified racing",
    "sourceRestrictions": "⚠ Track use only — not road legal.",
    "capturedAt": "2026-09-10T09:18:45.553Z"
  },
  {
    "websiteProductId": 282,
    "supplierSku": "16130T10",
    "brand": "HOOSIER",
    "pattern": "Kart Tyre T10 Soft",
    "size": "18.5X6.0-10",
    "category": "Karting",
    "productName": "Hoosier Kart Tyre T10 Soft — 18.5×6.0-10",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 2950,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Kart-Slick-Tire.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-18-5x6-0-10t10-16130t10/",
    "sourceSpecifications": "Item Code: 16130T10\nSize: 18.5×6.0-10\nCompound: Soft (T10)\nApplication: Kart Racing\nCompound Quick Guide:",
    "sourceRestrictions": "⚠ Designed for kart racing use only. Not intended for road use.",
    "capturedAt": "2026-09-10T09:18:46.150Z"
  },
  {
    "websiteProductId": 281,
    "supplierSku": "16110T20",
    "brand": "HOOSIER",
    "pattern": "Kart Tyre T20 Hard",
    "size": "18.0X11.0-10",
    "category": "Karting",
    "productName": "Hoosier Kart Tyre T20 Hard — 18.0×11.0-10",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 3350,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-Kart-Slick-Tire.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-18-0x11-0-10t20-16110t20/",
    "sourceSpecifications": "Item Code: 16110T20\nSize: 18.0×11.0-10\nCompound: Hard (T20)\nApplication: Kart Racing\nCompound Quick Guide:",
    "sourceRestrictions": "⚠ Designed for kart racing use only. Not intended for road use.",
    "capturedAt": "2026-09-10T09:18:46.736Z"
  },
  {
    "websiteProductId": 13,
    "supplierSku": "19300",
    "brand": "HOOSIER",
    "pattern": "Pro Street DOT Radial",
    "size": "31X16.50R15LT",
    "category": "Pro Street",
    "productName": "Hoosier Pro Street DOT Radial – 31×16.50R15 LT",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 14000,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/03/Hoosier-DOT-Drag-Radial.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-pro-street-d-o-t-radial-31-x-16-50r-15-lt-19300/",
    "sourceSpecifications": "",
    "sourceRestrictions": "",
    "capturedAt": "2026-09-10T09:18:47.377Z"
  },
  {
    "websiteProductId": 39,
    "supplierSku": "17421QTPRO",
    "brand": "HOOSIER",
    "pattern": "QT Pro Drag Tyre",
    "size": "26.0X11.5-15LT",
    "category": "Drag Tyres",
    "productName": "Hoosier QT Pro Drag Tyre – 26.0×11.5-15LT",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 7800,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-QT-Pro-Drag-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-drag-racing-slicks-26-11-5-15/",
    "sourceSpecifications": "Item Code: 17421QTPRO\nSize: 26.0×11.5-15LT\nConstruction: Bias-ply\nCompound: Soft drag (Quick Time Pro)\nTread: DOT-labelled, slick-style with minimal grooves\nApplication: Drag racing / dry strip use, limited street/strip\nWhere QT Pro Sits:",
    "sourceRestrictions": "⚠ Drag racing focused — DOT-labelled but not intended for daily driving.",
    "capturedAt": "2026-09-10T09:18:48.006Z"
  },
  {
    "websiteProductId": 49,
    "supplierSku": "17415QTPRO",
    "brand": "HOOSIER",
    "pattern": "QT Pro Drag Tyre",
    "size": "26.0X9.5-15LT",
    "category": "Drag Tyres",
    "productName": "Hoosier QT Pro Drag Tyre – 26.0×9.5-15LT",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 7500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-QT-Pro-Drag-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-quick-time-pro-d-o-t-drag-racing-tire-26-x-9-50-15-lt-17415qtpro/",
    "sourceSpecifications": "Item Code: 17415QTPRO\nSize: 26.0×9.5-15LT\nConstruction: Bias-ply\nCompound: Soft drag (Quick Time Pro)\nTread: DOT-labelled, slick-style with minimal grooves\nApplication: Drag racing / dry strip use, limited street/strip\nWhere QT Pro Sits:",
    "sourceRestrictions": "⚠ Drag racing focused — DOT-labelled but not intended for daily driving.",
    "capturedAt": "2026-09-10T09:18:48.686Z"
  },
  {
    "websiteProductId": 287,
    "supplierSku": "17606QTPRO",
    "brand": "HOOSIER",
    "pattern": "QT Pro Drag Tyre",
    "size": "28.0X13.5-15LT",
    "category": "Drag Tyres",
    "productName": "Hoosier QT Pro Drag Tyre – 28.0×13.5-15LT",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 8500,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-QT-Pro-Drag-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-28-0x13-5-15lt-17606qtpro/",
    "sourceSpecifications": "Item Code: 17606QTPRO\nSize: 28.0×13.5-15LT\nConstruction: Bias-ply\nCompound: Soft drag (Quick Time Pro)\nTread: DOT-labelled, slick-style with minimal grooves\nApplication: Drag racing / dry strip use, limited street/strip\nWhere QT Pro Sits:",
    "sourceRestrictions": "⚠ Drag racing focused — DOT-labelled but not intended for daily driving.",
    "capturedAt": "2026-09-10T09:18:49.309Z"
  },
  {
    "websiteProductId": 289,
    "supplierSku": "17652QTPRO",
    "brand": "HOOSIER",
    "pattern": "QT Pro Drag Tyre",
    "size": "28.0X14.5-17LT",
    "category": "Drag Tyres",
    "productName": "Hoosier QT Pro Drag Tyre – 28.0×14.5-17LT",
    "stockUnits": 0,
    "orderStatus": "PREORDER",
    "websiteStockDetail": "Available on backorder",
    "sellingPrice": 8800,
    "imageUrl": "https://hoosiertyres.co.za/wp-content/uploads/2026/04/Hoosier-QT-Pro-Drag-Tyre.webp",
    "sourceUrl": "https://hoosiertyres.co.za/product/hoosier-28-0x14-5-17lt-17652qtpro/",
    "sourceSpecifications": "Item Code: 17652QTPRO\nSize: 28.0×14.5-17LT\nConstruction: Bias-ply\nCompound: Soft drag (Quick Time Pro)\nTread: DOT-labelled, slick-style with minimal grooves\nApplication: Drag racing / dry strip use, limited street/strip\nWhere QT Pro Sits:",
    "sourceRestrictions": "⚠ Drag racing focused — DOT-labelled but not intended for daily driving.",
    "capturedAt": "2026-09-10T09:18:49.985Z"
  }
] as const;
