"""Extract the visually reviewed September CPT tyre tables, excluding the rims page."""
import argparse
import hashlib
import json
import re
from pathlib import Path
from pypdf import PdfReader

SECTIONS = [
    [('ANCHEE', 36)],
    [('SAILUN', 12), ('SONIX', 1), ('ANNAITE', 2)],
    [('ACCELUS', 13), ('FIREMAX', 8)],
    [('PIRELLI', 13), ('POWERTRAC', 2), ('HABILEAD', 12)],
    [('PROMETEON', 8), ('TAITONG', 9), ('MACROYAL', 2), ('ANCHEE', 2), ('DOUPRO', 1)],
    [('SUMITOMO', 1)],
    [('AEOLUS', 7), ('TECHHERO', 2), ('ROCKBUSTER', 9), ('ASCENSO', 3), ('ADVANCE', 1)],
    [('LUHE', 1)],
]

def extract(path):
    pdf = PdfReader(path)
    if len(pdf.pages) != 9:
        raise ValueError('Expected the reviewed nine-page September PDF')
    rows = []
    for page, sections in zip(pdf.pages, SECTIONS):
        lines = [m.groups() for line in page.extract_text().splitlines()
                 if (m := re.fullmatch(r'(\d.*\S)\s+(\d+)\s+R([\d,]+(?:\.\d+)?)', line.strip()))]
        if len(lines) != sum(count for _, count in sections):
            raise ValueError(f'Unexpected row count on page {len(rows)}: {len(lines)}')
        offset = 0
        for brand, count in sections:
            for description, units, price in lines[offset:offset+count]:
                rows.append(dict(brand=brand, description=description.upper(),
                                 size=description.split()[0].upper(), units=int(units),
                                 cost=float(price.replace(',', '')), page=pdf.pages.index(page)+1))
            offset += count
    return rows

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('pdf')
    parser.add_argument('--out', default='reports/royal-cpt-extracted.json')
    parser.add_argument('--baseline', required=True, help='Export from the existing Royal workbook publisher')
    args = parser.parse_args()
    rows = extract(args.pdf)
    baseline = json.loads(Path(args.baseline).read_text(encoding='utf-8'))
    normalize = lambda text: re.sub(r'[^A-Z0-9]', '', text.upper())
    for row in rows:
        # The PDF uses both Pirelli/Prometeon logos and places three Road-Buster
        # H108CE products under RockBuster. Retain their existing SKU/brand identity.
        brand = row['brand']
        if brand == 'PROMETEON':
            brand = 'PIRELLI PROMETEON'
        elif brand == 'ROCKBUSTER' and 'H108CE' in row['description']:
            brand = 'ROAD-BUSTER'
        key = normalize(brand + ' ' + row['description'])
        matches = [item for item in baseline if normalize(item['product_name']) == key]
        if len(matches) > 1:
            raise ValueError(f'Ambiguous match: {row}')
        if matches:
            original = matches[0]
            row.update(source_key=original['source_key'], sku=original['supplier_sku'],
                       before_units=original['stock_by_location']['CPT'], before_cost=original['cost_price'],
                       matched_name=original['product_name'])
        else:
            if row['brand'] != 'ANCHEE' or row['description'] != '195/60R15 (H/T) 88H AC808':
                raise ValueError(f'Unreviewed new product: {row}')
            row.update(source_key='royal-cpt-anchee-195-60r15-ac808-88h', sku='',
                       before_units=0, before_cost=None, matched_name=None)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(dict(source_file=Path(args.pdf).name,
                                   sha256=hashlib.sha256(Path(args.pdf).read_bytes()).hexdigest(),
                                   rows=rows), indent=2)+'\n', encoding='utf-8')
    data = [dict(sourceKey=r['source_key'], supplierSku=r['sku'], brand=r['brand'],
                 description=r['description'], size=r['size'], cost=r['cost'], units=r['units'],
                 page=r['page'], isNew=r['matched_name'] is None) for r in rows]
    Path('supplier_data/royalTyresCapeTownSeptember2026.mjs').write_text(
        '// Generated by scripts/prepare-royal-cpt-pdf.py from the visually reviewed PDF.\n'
        'export const ROYAL_CPT_SEPTEMBER_2026 = '+json.dumps(data, indent=2)+';\n', encoding='utf-8')
    print(json.dumps(dict(rows=len(rows), units=sum(row['units'] for row in rows))))
